### ISSUE TITLE
ngx-charts-dag not working with angular 2

### ISSUE THREAD

**Issue by kirtiesl** [swimlane/ngx-charts-dag#9]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

We have followed the steps mentioned here https://www.npmjs.com/package/@swimlane/ngx-charts-dag. Integrating ngx-charts-dag with angular 2.4.3 gives following error. Please let us know what is the issue and how we can integrate ngx-charts-dag with example.

error_handler.js:50 EXCEPTION: Uncaught (in promise): Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
      <div class="tooltip-content">
        <span *ngIf="!title">
          [ERROR ->]<ng-template
            [ngTemplateOutlet]="template"
            [ngOutletContext]="{ model: contex"): TooltipContentComponent@9:10
Error: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
      <div class="tooltip-content">
        <span *ngIf="!title">
          [ERROR ->]<ng-template
            [ngTemplateOutlet]="template"
            [ngOutletContext]="{ model: contex"): TooltipContentComponent@9:10
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:112777:27) [angular]
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:6967:16) [angular]
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:23539:19) [angular]
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:81533:68) [angular]
    at http://localhost:4200/vendor.bundle.js:81416:62 [angular]
    at Set.forEach (native) [angular]
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:81416:19) [angular]
    at createResult (http://localhost:4200/vendor.bundle.js:81299:19) [angular]
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:34902:37) [angular]
    at Zone.run (http://localhost:4200/vendor.bundle.js:155836:43) [angular => angular]
    at http://localhost:4200/vendor.bundle.js:156232:57 [angular]

**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ngx-charts-dag version:** 2.0.0

* **Angular version:** 2.4.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by marjan-georgiev** [comment]
Use ngx-charts-dag version 1.0.0

**Comment by kirtiesl** [comment]
ngx-charts-dag version 1.0.0 gives below error:
Cannot read property 'map' of undefined

**Comment by marjan-georgiev** [comment]
How are you pass your data? Check the demo on how to use the component:
https://github.com/swimlane/ngx-charts-dag/blob/1.0.0/demo/app.component.ts

**Comment by kirtiesl** [comment]
passing data as given in the https://github.com/swimlane/ngx-charts-dag/blob/1.0.0/demo/app.component.ts gives error:
EXCEPTION: Uncaught (in promise): TypeError: Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at DirectedGraphComponent../src/directed-graph/directed-graph.component.ts.DirectedGraphComponent.getSeriesDomain (http://localhost:4200/0.chunk.js:101578:26)
    at http://localhost:4200/0.chunk.js:101236:40
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:154808:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:34905:37)
    at ZoneDelegate.invoke (http://localhost:4200/vendor.bundle.js:154807:32)
    at Zone.run (http://localhost:4200/vendor.bundle.js:154692:43)
    at NgZone.run (http://localhost:4200/vendor.bundle.js:34774:62)
    at DirectedGraphComponent../src/directed-graph/directed-graph.component.ts.DirectedGraphComponent.update (http://localhost:4200/0.chunk.js:101229:19)
    at DirectedGraphComponent../src/common/base-chart.component.ts.BaseChartComponent.ngOnChanges (http://localhost:4200/0.chunk.js:62993:14)
    at Wrapper_DirectedGraphComponent.ngDoCheck (/DirectedGraphModule/DirectedGraphComponent/wrapper.ngfactory.js:283:18)
    at CompiledTemplate.proxyViewClass.View_NetworkComponent0.detectChangesInternal (/RealtimeModule/NetworkComponent/component.ngfactory.js:277:40)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:121485:14)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:121470:18)
    at CompiledTemplate.proxyViewClass.View_NetworkComponent_Host0.detectChangesInternal (/RealtimeModule/NetworkComponent/host.ngfactory.js:27:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:121485:14)

**Comment by marjan-georgiev** [comment]
Are you fetching that data asynchronously? If you are, you might want to `*ngIf` the component until the data is fetched and ready.

**Comment by kirtiesl** [comment]
Thanks. It works.
